### ISSUE TITLE
How do I use this with gtags?

### ISSUE THREAD

**Issue by JuniorSuperTux** [delphinus/cmp-ctags#2]
As title

**Comment by delphinus** [comment]
This plugin is for Universal Ctags. Not for global (gtags). I googled and find you can use `gtags` with `ctags`' options by `--with-universal-ctags` option. You can use that, maybe. 

[How to install GNU Global with universall ctags support on mac OS](https://gist.github.com/carakan/60496e0f05033417be2352419639fcc5)

**Comment by delphinus** [comment]
This plugin is for Universal Ctags. Not for global (gtags). I googled and find you can use `gtags` with `ctags`' options by `--with-universal-ctags` option. You can use that, maybe. 

[How to install GNU Global with universall ctags support on mac OS](https://gist.github.com/carakan/60496e0f05033417be2352419639fcc5)
