### ISSUE TITLE
Complete project wide tags

### ISSUE THREAD

**Issue by GordianDziwis** [delphinus/cmp-ctags#6]
Is it possible to show not only the tags associated with the current buffer, but all tags inside the tags file?

**Comment by matu3ba** [comment]
Use the inbuild: https://stackoverflow.com/questions/49480770/vim-get-all-tags-of-a-buffer
context https://vimdoc.sourceforge.net/htmldoc/options.html#'tagbsearch'

**Comment by a73s** [comment]
I am probably misunderstanding but I do not see how this is helpful. I am trying to be able to get all tags into the completion list. Is this the same thing?
